version: '3'
services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - 3000
    ports:
      - '3000:3000'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 3001
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
      # Inside the container, don't try to override this folder, just leave as is
